return PlaceObj('ModDef', {
	'title', "Colonists need Oxygen not domes",
	'description', "Reduces air and water requirements of all domes (once built) to zero, also somwhat reduces power requirements.\n\nIncreases air, water and power requirements for each colonist living inside a dome.\n\nThe following are the default options:\n* 50 Power for every 1000 colonists.\n* 10 Oxygen and 10 Water for every 1000 colonists in an ordinary dome.\n* 25 Water for every 1000 colonists in the Geoscape dome and capital city.\n\nPermission is granted to update this mod to support the latest version of the game if I'm not around to do it myself.",
	'last_changes', "reorganised stuff",
	'id', "VdfZ0nh",
	'steam_id', "1807549458",
	'pops_desktop_uuid', "409d8ba5-fd04-4ab4-a514-7a1f389f4b6b",
	'pops_any_uuid', "6e1f8f7e-de56-4ca4-a7e9-95fd5ee51928",
	'author', "mrudat",
	'version_minor', 3,
	'version', 37,
	'lua_revision', 233360,
	'saved_with_revision', 249143,
	'code', {
		"Code/ColonistsNeedOxygenNotDomes.lua",
	},
	'has_options', true,
	'saved', 1572295795,
	'TagGameplay', true,
})